const
	ITEM = 'item',
	COLOR = 'color',
	ACTIVE = 'active',
	DISABLED = 'disabled',
	FUNCTION = 'function',
	SPEARATOR = 'spearator',
	WHITESPACE = 'whitespace',
	BACKGROUND = 'background',
	FRONTGROUND = 'frontground';

export const
	FUNCTION_ITEM_HEIGHT = `${FUNCTION}-${ITEM}-height`,
	FUNCTION_ITEM_WHITESPACE = `${FUNCTION}-${ITEM}-${WHITESPACE}`,
	DISABLED_BACKGROUND_COLOR = `${DISABLED}-${BACKGROUND}-${COLOR}`,
	DISABLED_FRONTGROUND_COLOR = `${DISABLED}-${FRONTGROUND}-${COLOR}`,
	ACTIVE_BACKGROUND_COLOR = `${ACTIVE}-${BACKGROUND}-${COLOR}`,
	ACTIVE_FRONTGROUND_COLOR = `${ACTIVE}-${FRONTGROUND}-${COLOR}`,
	BACKGROUND_COLOR = `${BACKGROUND}-${COLOR}`,
	FRONTGROUND_COLOR = `${FRONTGROUND}-${COLOR}`,
	OUTLINE_COLOR = `outline-${COLOR}`,
	SPEARATOR_COLOR = `${SPEARATOR}-${COLOR}`,
	SPEARATOR_WHITESPACE_X = `${SPEARATOR}-${WHITESPACE}-x`,
	WHITESPACE_Y = `${WHITESPACE}-y`,
	SPACE_SM = 'space-sm',
	BAR_HEIGHT = 'bar-height';