export const
	ACTIVE = 'a',
	HAS_MNEMONIC = 'h',
	BUTTON_LIST = 'b',
	BAR_ELEMENT = 'e',
	FOCUSING_BUTTON = 'f',

	DEACTIVE = 'D',
	ACTIVATE = 'V',
	TOGGLE = 'T',
	APPEND_BUTTON = 'A',
	FOCUS_BUTTON = 'F',
	BLUR_FOCUSING_BUTTON = 'B',
	NEXT = 'N';