export const
	ACTIVE = 'a',
	HAS_MNEMONIC = 'h',
	BUTTON_LIST = 'b',
	BAR_ELEMENT = 'e',
	FOCUSING_BUTTON = 'f',

	DEACTIVE = 'D',
	APPEND_BUTTON = 'A',
	FOCUS_BUTTON = 'F',
	BLUR_FOCUSING_BUTTON = 'B',
	TOGGLE_ACTIVE = 'T';